### ISSUE TITLE
Error With Navwalker WP 4.9.1

### ISSUE THREAD

**Issue by minimallinux** [robjameseu/BulmaWP#1]
Hi, I am getting an error with the Navwalker include file, on line 21 "Trying to get property of a non-object"
Notice: Trying to get property of non-object in /var/www/vhost3.com/minimallinux/wp-content/themes/BulmaWP/includes/php/bulmaWP-navwalker.php on line 21

Tips welcome! Thanks

**Comment by robjameseu** [comment]
Hey minimallinux, 

My mistake here the uploaded code is out of date and should be deleted.

I’ve been working on a complete rebuild of the bulmawp theme of which I hope to push soon.
